### ISSUE TITLE
Curiosity question

### ISSUE THREAD

**Issue by 7sharp9** [krauthaufen/FSharp.Quotation.Disassembler#1]
I was just curious about this library and could not quite figure out what it was trying to achieve?

What is the intension to give to the function:

```
static member GetDisassembledDefinition (m : MethodBase)
```

Purely a reflected definition attributed function?

**Comment by krauthaufen** [comment]
Hi, the thing was actually intended to disassemble il code to f# expr.
whenever a reflected defintion is available it would obviously prefer that one over disassembling IL.

I started by using ILSpy's disassembler which gives a c# like syntax tree. However this tree is relatively hard to translate to F# due to various imperative constructs (return in loops, etc.)

However the whole thing could be useful when translating to some other language like (as we do) GLSL since it could give F# expressions even for C# methods.
